### ISSUE TITLE
Gamekings Extra video's 

### ISSUE THREAD

**Issue by Amelandbor** [skipmodea1/plugin.video.gamekings#1]
Ik zat te denken dat het misschien een mooie toevoeging zou zijn om de extra video's ook toe te voegen. 

Ik heb zelf ook al even gekeken om het toe te voegen dmv de bestaande methode, moet alleen nog even een manier zien te vinden om de video url te krijgen. Dit werkt anders dan via og:video.
Het is misschien makkelijker om een link te maken naar het youtube channel die dan wordt geopend in de yotube plugin? 

Laat maar even weten welke manier de voorkeur heeft voordat ik er druk mee aan de slag ga.

**Comment by skipmodea1** [comment]
Welke extra video's bedoel je precies? Link?

**Comment by Amelandbor** [comment]
Deze: http://www.gamekings.tv/tag/Gamekings-Extra/
Ze staan echter ook allemaal op youtube:
https://www.youtube.com/user/Gamekingsextra

2014-11-13 5:51 GMT+01:00 skipmodea1 notifications@github.com:

**Comment by skipmodea1** [comment]
Ja leuk, ik kende die videos helemaal niet. 

Ik heb nog gekeken naar hoe dat zou moeten voor de gamekings links:

Ergens in de pagina staat iets als dit:
gogoVideo

(92055,"MjAxNDExMTRfRXh0cmEubXA0LGh0dHA6Ly93d3cuZ2FtZWtpbmdzLnR2L3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE0MTExNF9FeHRyYV9zcGxhc2gtMTAyNHg1NzYuanBnLEdhbWVraW5ncyBFeHRyYTogV2Vsa2UgZ2FtZXMgc3BlbGVuIHdpaiBkaXQgbmFqYWFyPw==");

Dat stukje tussen quotes (dus van "Mj....==") is base 64 gecodeerd. Als je dat decodeert rolt er dit uit:
20141114_Extra.mp4,http://www.gamekings.tv/wp-content/uploads/20141114_Extra_splash-1024x576.jpg,Gamekings Extra: Welke games spelen wij dit najaar?

Dan heb je dus de naam van de file. 
Zie bv dumpert_play van mijn dumpert addon voor het decoderen van een base64 string.

Je zou dus gamekings_play kunnen aanpassen zodat ie voor de extra vids niet naar og zoekt, maar naar 'gogoVideo' ofzo. En dan decoderen van de base 64 string. En dan daarvoor stream enzo plakken zoals nu al gebeurd in gamekings_play.

Dat lijkt me de voorkeur hebben. Mocht het helemaal niet lukken dan kunnen we altijd nog besluiten het met youtube te doen.

Succes! Ik hoor het dan wel...
